# Generated by Django 3.2.5 on 2021-07-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditor', '0006_alter_creditor_master_homeno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditor_master',
            name='homeno',
        ),
        migrations.AlterField(
            model_name='creditor_master',
            name='officeno',
            field=models.CharField(max_length=10),
        ),
    ]
