# Generated by Django 3.2.5 on 2021-07-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_vehicle_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='remarks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
