# Generated by Django 3.2.5 on 2021-07-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0004_auto_20210715_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank_master',
            name='dieselbefore',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tank_master',
            name='petrolbefore',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
